name: radio_garden
description: Radio Garden discord bot.
version: 0.0.1
homepage: https://github.com/tomassasovsky/radio_garden
repository: https://github.com/tomassasovsky/radio_garden
documentation: https://github.com/tomassasovsky/radio_garden
issue_tracker: https://github.com/tomassasovsky/radio_garden/issues
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dotenv: ^4.0.1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  logging: ^1.1.0
  mongo_dart: ^0.8.1
  nyxx: ^4.3.0
  nyxx_commands:
    git:
      url: https://github.com/nyxx-discord/nyxx_commands.git
      ref: next
  nyxx_interactions: ^4.4.0
  nyxx_lavalink: ^3.1.0
  nyxx_pagination: ^2.3.0
  prometheus_client: ^1.0.0+1
  prometheus_client_shelf: ^1.0.0+1
  retry: ^3.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  slang: ^3.5.0
  time_ago_provider: ^4.2.0
  usage: ^4.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: ^3.0.0
  build_version: ^2.1.1
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  slang_build_runner: ^3.5.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0

assets:
  - .env/
